# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

global IN_DIRE,OUT_DIRE,IYEAR,IMONTH,IDAY0,IM,JM,KB
global LOG_TSR_EL,LOG_OBS_EL,LOG_TSR_VEL, LOG_OBS_VEL, TSR_LAYER_VEL
global LOG_TSR_S, LOG_OBS_S, TSR_LAYER_S, LOG_TSR_SEC, TSR_BEG, TSR_END, TSR_LAG
global TSR_SEC_BEG, TSR_SEC_END, TSR_SEC_LAG, N_FPT, DMIN
global LOG_OPT, LOG_EPT
global EPT_TIME, LOG_VPT_UV, LOG_VPT_SD, VPT_TIME, VPT_LAYER, VPT_INTERVAL
global VPT_SCALE 
global LOG_FIELD, LOG_SPT, SPT_TIME, SPT_LAYER, LOG_RSPT, RSPT_LAYER, LOG_SED
global SED_TIME, SED_LAYER, LOG_FIELD_RSED, RSED_LAYER, RS_MIN_DEP, LOG_TAU, TAU_TIME
global FPT_COORDINATE, FPT_XMIN, FPT_XMAX, FPT_YMIN, FPT_YMAX, FPT_COLOR_TYPE;
global LOG_SEC_S, SEC_S_TIME, LOG_SEC_RS, LOG_SEC_SED, SEC_SED_TIME, LOG_SEC_RSED_FLUX
global SEC_P_TYPE, SEC_NUM, SEC_RESOLUTION, SEC_MAX_HIGHT, SEC_CONTROL_POINTS
global xr, yr,SEC_CONTROL_POINT

