# -*- coding: utf-8 -*-

import globalvar as gl

#============ Reading Draw Setting File =======================
with open('Draw_setting.txt') as f:
        lines = f.readlines()

inptdict={}.fromkeys(('IN_DIRE','OUT_DIRE','IYEAR','IMONTH','IDAY0','IM','JM','KB','LOG_TSR_EL','LOG_OBS_EL','LOG_TSR_VEL','LOG_OBS_VEL','TSR_LAYER_VEL','LOG_TSR_S','LOG_OBS_S','TSR_LAYER_S','LOG_TSR_SEC','TSR_BEG',
'TSR_END','TSR_LAG','TSR_SEC_BEG','TSR_SEC_END','TSR_SEC_LAG','LOG_FIELD','N_FPT','DMIN','LOG_OPT','LOG_EPT','EPT_TIME','LOG_VPT_UV','LOG_VPT_SD','VPT_TIME','VPT_LAYER','VPT_INTERVAL','VPT_SCALE',
'LOG_SPT','SPT_TIME','SPT_LAYER','LOG_RSPT','RSPT_LAYER','LOG_SED','SED_TIME','SED_LAYER','LOG_FIELD_RCUR','RCUR_LAYER','LOG_FIELD_RSED','RSED_LAYER','RS_MIN_DEP','LOG_TAU','TAU_TIME','FPT_COORDINATE',
'FPT_XMIN','FPT_XMAX','FPT_YMIN','FPT_YMAX','FPT_COLOR_TYPE','LOG_SEC_S','SEC_S_TIME','LOG_SEC_RS','LOG_SEC_SED','SEC_SED_TIME','LOG_SEC_RSED_FLUX','SEC_NUM','SEC_CONTROL_POINTS','SEC_RESOLUTION','SEC_MAX_HIGHT'))


lndict=dict((['IN_DIRE',3],['OUT_DIRE',4],['IYEAR',6],['IMONTH',7],['IDAY0',8],['IM',10],['JM',11],['KB',12],
['LOG_TSR_EL',14],['LOG_OBS_EL',15],['LOG_TSR_VEL',16],['LOG_OBS_VEL',17],['TSR_LAYER_VEL',18],['LOG_TSR_S',19],['LOG_OBS_S',20],
['TSR_LAYER_S',21],['LOG_TSR_SEC',22],['TSR_BEG',23],['TSR_END',24],['TSR_LAG',25],['TSR_SEC_BEG',26],['TSR_SEC_END',27],['TSR_SEC_LAG',28],
['LOG_FIELD',30],['N_FPT',31],['DMIN',32],['LOG_OPT',33],['LOG_EPT',34],['EPT_TIME',35],['LOG_VPT_UV',36],['LOG_VPT_SD',37],
['VPT_TIME',38],['VPT_LAYER',39],['VPT_INTERVAL',40],['VPT_SCALE',41],['LOG_SPT',42],['SPT_TIME',43],['SPT_LAYER',44],['LOG_RSPT',45],
['RSPT_LAYER',46],['LOG_SED',47],['SED_TIME',48],['SED_LAYER',49],['LOG_FIELD_RCUR',50],['RCUR_LAYER',51],['LOG_FIELD_RSED',52],
['RSED_LAYER',53],['RS_MIN_DEP',54],['LOG_TAU',55],['TAU_TIME',56],['FPT_COORDINATE',57],['FPT_XMIN',58],['FPT_XMAX',59],['FPT_YMIN',60],
['FPT_YMAX',61],['FPT_COLOR_TYPE',62],['LOG_SEC_S',64],['SEC_S_TIME',65],['LOG_SEC_RS',66],['LOG_SEC_SED',67],['SEC_SED_TIME',68],
['LOG_SEC_RSED_FLUX',69],['SEC_NUM',70],['SEC_CONTROL_POINTS',71],['SEC_RESOLUTION',73],['SEC_MAX_HIGHT',74]))





for key in lndict.keys():
    data = lines[lndict[key]-1].split()
    print 'key= %s, value= %s' % (key,data[1])
    inptdict[key]=data[1]
    
    SEC_CONTROL_POINT = lines[71].split(';')    
    
       

iptnm=['IN_DIRE','OUT_DIRE','IYEAR','IMONTH','IDAY0','IM','JM','KB','LOG_TSR_EL','LOG_OBS_EL','LOG_TSR_VEL','LOG_OBS_VEL','TSR_LAYER_VEL','LOG_TSR_S','LOG_OBS_S','TSR_LAYER_S','LOG_TSR_SEC','TSR_BEG',
'TSR_END','TSR_LAG','TSR_SEC_BEG','TSR_SEC_END','TSR_SEC_LAG','LOG_FIELD','N_FPT','DMIN','LOG_OPT','LOG_EPT','EPT_TIME','LOG_VPT_UV','LOG_VPT_SD','VPT_TIME','VPT_LAYER','VPT_INTERVAL','VPT_SCALE',
'LOG_SPT','SPT_TIME','SPT_LAYER','LOG_RSPT','RSPT_LAYER','LOG_SED','SED_TIME','SED_LAYER','LOG_FIELD_RCUR','RCUR_LAYER','LOG_FIELD_RSED','RSED_LAYER','RS_MIN_DEP','LOG_TAU','TAU_TIME','FPT_COORDINATE',
'FPT_XMIN','FPT_XMAX','FPT_YMIN','FPT_YMAX','FPT_COLOR_TYPE','LOG_SEC_S','SEC_S_TIME','LOG_SEC_RS','LOG_SEC_SED','SEC_SED_TIME','LOG_SEC_RSED_FLUX','SEC_NUM','SEC_CONTROL_POINTS','SEC_RESOLUTION','SEC_MAX_HIGHT']



'''
gl.IN_DIRE  	
gl.OUT_DIRE 
gl.IYEAR		
gl.IMONTH	
gl.IDAY0		
gl.IM	
gl.JM	
gl.KB
gl.LOG_TSR_EL	
gl.LOG_OBS_EL
gl.LOG_TSR_VEL
gl.LOG_OBS_VEL
gl.TSR_LAYER_VEL
gl.LOG_TSR_S
gl.LOG_OBS_S
gl.TSR_LAYER_S	 
gl.LOG_TSR_SEC
gl.TSR_BEG
gl.TSR_END
gl.TSR_LAG
gl.TSR_SEC_BEG
gl.TSR_SEC_END
gl.TSR_SEC_LAG
gl.LOG_FIELD
gl.N_FPT
gl.DMIN
gl.LOG_OPT
gl.LOG_EPT
gl.EPT_TIME
gl.LOG_VPT_UV
gl.LOG_VPT_SD
gl.VPT_TIME
gl.VPT_LAYER
gl.VPT_INTERVAL
gl.VPT_SCALE
gl.LOG_SPT
gl.SPT_TIME
gl.SPT_LAYER
gl.LOG_RSPT
gl.RSPT_LAYER
gl.LOG_SED
gl.SED_TIME
gl.SED_LAYER
gl.LOG_FIELD_RCUR
gl.RCUR_LAYER
gl.LOG_FIELD_RSED
gl.RSED_LAYER
gl.RS_MIN_DEP
gl.LOG_TAU
gl.TAU_TIME
gl.FPT_COORDINATE
gl.FPT_XMIN	
gl.FPT_XMAX
gl.FPT_YMIN
gl.FPT_YMAX
gl.FPT_COLOR_TYPE
gl.LOG_SEC_S
gl.SEC_S_TIME
gl.LOG_SEC_RS
gl.LOG_SEC_SED
gl.SEC_SED_TIME
gl.LOG_SEC_RSED_FLUX
gl.SEC_NUM
gl.SEC_CONTROL_POINTS
gl.SEC_RESOLUTION
gl.SEC_MAX_HIGHT
'''


